# Generated by Django 5.1.2 on 2024-11-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='inconnu', max_length=30)),
                ('email', models.EmailField(default='kfb@gmail.com', max_length=254)),
                ('message', models.TextField(default='message')),
                ('date_send', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Realisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sable', models.CharField(choices=[('SABLE SANAGA', 'SABLE SANAGA'), ('SABLE FIN', 'SABLE FIN')], max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='realisations/')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('photo', models.ImageField(upload_to='testimonials/')),
                ('role', models.CharField(max_length=100, verbose_name='Métier')),
                ('comment', models.TextField(max_length=210, verbose_name='Commentaire')),
                ('stars', models.PositiveIntegerField(choices=[(0, 'Très mécontent'), (1, 'Mécontent'), (2, 'Indifférent'), (3, 'Satisfait'), (4, 'Assez Satisfait'), (5, 'Très Satisfait')], default=5, verbose_name='étoiles')),
                ('published', models.BooleanField(default=True, verbose_name='publié')),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['-id'],
            },
        ),
    ]
